[package]
name = "whiskers-web-demo"
version = "0.1.0-alpha.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
whiskers = { path = "../whiskers", features = ["viewer"] }
itertools.workspace = true
