[package]
name = "vsvg-sketch-derive"
version = "0.1.0-alpha.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.37", features = ["full"] }
quote = "1.0.33"
proc-macro2 = "1.0.67"
convert_case.workspace = true
